---
- name: build docker image
  docker_image:
    path: /Users/*****/Documents/Projects/crude_deal/test_deal_08032019/app-crudedealsdb/crudedeal-service/
    name: "{{ image_name }}"
    tag: "{{ image_version }}"

- name: docker login (must `--no-include-email`)
  shell: "$(aws ecr get-login --region {{ region }} --no-include-email)"
  args:
      executable: /bin/bash

- name: create repository
  ecs_ecr:
    name: "{{ image_name }}"
    aws_access_key: "{{ key_id }}"
    aws_secret_key: "{{ access_key }}"
    region: "{{ region }}"
  register: ecr_repo

- name: add tag
  docker_image:
    name: "{{ image_name }}:{{ image_version }}"
    repository: "{{ ecr_repo.repository.repositoryUri }}"
    tag: "{{ ecr_repo.repository.repositoryUri }}:{{ image_version }}"

- name: push image to ecr
  docker_image:
    name: "{{ ecr_repo.repository.repositoryUri }}:{{ image_version }}"
    push: yes
