---
---
- name: Build Maven app backend.
  command: /usr/local/bin/mvn clean package chdir=/Users/kiranchanda/Projects/ecspush_ansible/ansible-push2ecr/crudedeal-service/

- name: Build docker image from dockerfile.
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ git_code_version.after }}"
    source: build
    build:
      path: "{{item.directory}}"
      pull: true
    state: present
  with_items:
    - { name: crudedeal-service-api, tag: latest, directory: "/Users/kiranchanda/Projects/ecspush_ansible/ansible-push2ecr/crudedeal-service/" }
    # - { name: web, tag: latest, directory:   }

- name: Tag image with AWS ECR registry, repo and image tag name.
  docker_image:
    name: "{{ image_name }}:{{ git_code_version.after }}"
    repository: "{{ ecr_registry }}/{{ repo }}"
    tag: "{{ git_code_version.after }}"

- name: docker ecr login (must `--no-include-email`)
  shell: "$(aws ecr get-login --region {{ region }} --no-include-email)"
  args:
      executable: /bin/bash

- name: push image to ecr.
  docker_image:
    name: "{{ ecr_registry }}/{{ repo }}:{{ git_code_version.after }}"
    push: yes

- debug: msg="SHA-1 before git update is {{ git_code_version.before }}"
- debug: msg="SHA-1 after git update is {{ git_code_version.after }}"
