---
# tasks file for parameter_store
#
# - name: Create or update key/value pair in aws parameter store
#   aws_ssm_parameter_store:
#     name: "{{ item.key }}"
#     description: "{{ item.description }}"
#     value: "{{ item.value }}"
#     state: present
#   with_items:
#     - { key: testuser1, value: value54567, description: descrip1 }
#     - { key: testuser2, value: value2, description: descrip2 }
#     - { key: testuser3, value: value3, description: descrip3 }


- name: Create or update key/value pair in aws parameter store
  aws_ssm_parameter_store:
    name: "{{ item.key }}"
    # description: "{{ item.value.desc }}"
    value: "{{ item.value}}"
    state: present
  loop: "{{ lookup('dict', aws_crude_param_store) }}"
